name = "daxecord"
author = "encode42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7fd659f599413344551e3767de6c1c8e94b21f85a1d3615f1b6130de2461de0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
