name = "daxecord"
author = "encode42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da23d3c2ff414708624116ab204dc1425388465621d302f584c6dbeccb87befe"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
