name = "daxecraft"
author = "encode42"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3abb1c5a11c84dd8a3f6b42ccb645b4f8f8016006cda3de3957c0e90d76ce97"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
